var sys = require("sys"),
    path = require("path"),
    util = require("util"),
    http = require("http"),
    _ = require("underscore"),
    connect = require("connect")

var nothingElseMatters = {
  "name": "Nothing Else Matters",
  "cover": "/static/nothing-else-matters.jpg",
  "audio": "/static/nothing-else-matters.mp3",
  "lyrics": [[
      { word: 'So', timing: 0 },
      { word: 'close,', timing: 0 },
      { word: 'no', timing: 0 },
      { word: 'matter', timing: 0 },
      { word: 'how', timing: 0 },
      { word: 'far', timing: 0 } ],
    [ { word: 'Couldn\'t', timing: 0 },
      { word: 'be', timing: 0 },
      { word: 'much', timing: 0 },
      { word: 'more', timing: 0 },
      { word: 'from', timing: 0 },
      { word: 'the', timing: 0 },
      { word: 'heart', timing: 0 } ],
    [ { word: 'Forever', timing: 0 },
      { word: 'trust', timing: 0 },
      { word: 'in', timing: 0 },
      { word: 'who', timing: 0 },
      { word: 'we', timing: 0 },
      { word: 'are', timing: 0 } ],
    [ { word: 'And', timing: 0 },
      { word: 'nothing', timing: 0 },
      { word: 'else', timing: 0 },
      { word: 'matters', timing: 0 } ],
    [ { word: 'Never', timing: 0 },
      { word: 'opened', timing: 0 },
      { word: 'myself', timing: 0 },
      { word: 'this', timing: 0 },
      { word: 'way', timing: 0 } ],
    [ { word: 'Life', timing: 0 },
      { word: 'is', timing: 0 },
      { word: 'ours,', timing: 0 },
      { word: 'we', timing: 0 },
      { word: 'live', timing: 0 },
      { word: 'it', timing: 0 },
      { word: 'our', timing: 0 },
      { word: 'way', timing: 0 } ],
    [ { word: 'All', timing: 0 },
      { word: 'these', timing: 0 },
      { word: 'words,', timing: 0 },
      { word: 'I', timing: 0 },
      { word: 'don\'t', timing: 0 },
      { word: 'just', timing: 0 },
      { word: 'say', timing: 0 } ],
    [ { word: 'And', timing: 0 },
      { word: 'nothing', timing: 0 },
      { word: 'else', timing: 0 },
      { word: 'matters', timing: 0 } ],
    [ { word: 'Trust', timing: 0 },
      { word: 'I', timing: 0 },
      { word: 'seek', timing: 0 },
      { word: 'and', timing: 0 },
      { word: 'I', timing: 0 },
      { word: 'find', timing: 0 },
      { word: 'in', timing: 0 },
      { word: 'you', timing: 0 } ],
    [ { word: 'Every', timing: 0 },
      { word: 'day', timing: 0 },
      { word: 'for', timing: 0 },
      { word: 'us', timing: 0 },
      { word: 'something', timing: 0 },
      { word: 'new', timing: 0 } ],
    [ { word: 'Open', timing: 0 },
      { word: 'mind', timing: 0 },
      { word: 'for', timing: 0 },
      { word: 'a', timing: 0 },
      { word: 'different', timing: 0 },
      { word: 'view', timing: 0 } ],
    [ { word: 'And', timing: 0 },
      { word: 'nothing', timing: 0 },
      { word: 'else', timing: 0 },
      { word: 'matters', timing: 0 } ],
    [ { word: 'Never', timing: 0 },
      { word: 'cared', timing: 0 },
      { word: 'for', timing: 0 },
      { word: 'what', timing: 0 },
      { word: 'they', timing: 0 },
      { word: 'do', timing: 0 } ],
    [ { word: 'Never', timing: 0 },
      { word: 'cared', timing: 0 },
      { word: 'for', timing: 0 },
      { word: 'what', timing: 0 },
      { word: 'they', timing: 0 },
      { word: 'know', timing: 0 } ],
    [ { word: 'And', timing: 0 },
      { word: 'I', timing: 0 },
      { word: 'know', timing: 0 } ],
    [ { word: 'So', timing: 0 },
      { word: 'close,', timing: 0 },
      { word: 'no', timing: 0 },
      { word: 'matter', timing: 0 },
      { word: 'how', timing: 0 },
      { word: 'far', timing: 0 } ],
    [ { word: 'Couldn\'t', timing: 0 },
      { word: 'be', timing: 0 },
      { word: 'much', timing: 0 },
      { word: 'more', timing: 0 },
      { word: 'from', timing: 0 },
      { word: 'the', timing: 0 },
      { word: 'heart', timing: 0 } ],
    [ { word: 'Forever', timing: 0 },
      { word: 'trusting', timing: 0 },
      { word: 'who', timing: 0 },
      { word: 'we', timing: 0 },
      { word: 'are', timing: 0 } ],
    [ { word: 'And', timing: 0 },
      { word: 'nothing', timing: 0 },
      { word: 'else', timing: 0 },
      { word: 'matters', timing: 0 } ],
    [ { word: 'Never', timing: 0 },
      { word: 'cared', timing: 0 },
      { word: 'for', timing: 0 },
      { word: 'what', timing: 0 },
      { word: 'they', timing: 0 },
      { word: 'do', timing: 0 } ],
    [ { word: 'Never', timing: 0 },
      { word: 'cared', timing: 0 },
      { word: 'for', timing: 0 },
      { word: 'what', timing: 0 },
      { word: 'they', timing: 0 },
      { word: 'know', timing: 0 } ],
    [ { word: 'And', timing: 0 },
      { word: 'I', timing: 0 },
      { word: 'know,', timing: 0 },
      { word: 'yeah', timing: 0 } ],
    [ { word: 'I', timing: 0 },
      { word: 'never', timing: 0 },
      { word: 'opened', timing: 0 },
      { word: 'myself', timing: 0 },
      { word: 'this', timing: 0 },
      { word: 'way', timing: 0 } ],
    [ { word: 'Life', timing: 0 },
      { word: 'is', timing: 0 },
      { word: 'ours,', timing: 0 },
      { word: 'we', timing: 0 },
      { word: 'live', timing: 0 },
      { word: 'it', timing: 0 },
      { word: 'our', timing: 0 },
      { word: 'way', timing: 0 } ],
    [ { word: 'All', timing: 0 },
      { word: 'these', timing: 0 },
      { word: 'words,', timing: 0 },
      { word: 'I', timing: 0 },
      { word: 'don\'t', timing: 0 },
      { word: 'just', timing: 0 },
      { word: 'say', timing: 0 } ],
    [ { word: 'And', timing: 0 },
      { word: 'nothing', timing: 0 },
      { word: 'else', timing: 0 },
      { word: 'matters', timing: 0 } ],
    [ { word: 'Trust', timing: 0 },
      { word: 'I', timing: 0 },
      { word: 'seek', timing: 0 },
      { word: 'and', timing: 0 },
      { word: 'I', timing: 0 },
      { word: 'find', timing: 0 },
      { word: 'in', timing: 0 },
      { word: 'you', timing: 0 } ],
    [ { word: 'Every', timing: 0 },
      { word: 'day', timing: 0 },
      { word: 'for', timing: 0 },
      { word: 'us', timing: 0 },
      { word: 'something', timing: 0 },
      { word: 'new', timing: 0 } ],
    [ { word: 'Open', timing: 0 },
      { word: 'mind', timing: 0 },
      { word: 'for', timing: 0 },
      { word: 'a', timing: 0 },
      { word: 'different', timing: 0 },
      { word: 'view', timing: 0 } ],
    [ { word: 'And', timing: 0 },
      { word: 'nothing', timing: 0 },
      { word: 'else', timing: 0 },
      { word: 'matters', timing: 0 } ],
    [ { word: 'Never', timing: 0 },
      { word: 'cared', timing: 0 },
      { word: 'for', timing: 0 },
      { word: 'what', timing: 0 },
      { word: 'they', timing: 0 },
      { word: 'say', timing: 0 } ],
    [ { word: 'Never', timing: 0 },
      { word: 'cared', timing: 0 },
      { word: 'for', timing: 0 },
      { word: 'games', timing: 0 },
      { word: 'they', timing: 0 },
      { word: 'play', timing: 0 } ],
    [ { word: 'Never', timing: 0 },
      { word: 'cared', timing: 0 },
      { word: 'for', timing: 0 },
      { word: 'what', timing: 0 },
      { word: 'they', timing: 0 },
      { word: 'do', timing: 0 } ],
    [ { word: 'Never', timing: 0 },
      { word: 'cared', timing: 0 },
      { word: 'for', timing: 0 },
      { word: 'what', timing: 0 },
      { word: 'they', timing: 0 },
      { word: 'know', timing: 0 } ],
    [ { word: 'And', timing: 0 },
      { word: 'I', timing: 0 },
      { word: 'know,', timing: 0 },
      { word: 'ooh,', timing: 0 },
      { word: 'yeah', timing: 0 } ],
    [ { word: 'So', timing: 0 },
      { word: 'close,', timing: 0 },
      { word: 'no', timing: 0 },
      { word: 'matter', timing: 0 },
      { word: 'how', timing: 0 },
      { word: 'far', timing: 0 } ],
    [ { word: 'Couldn\'t', timing: 0 },
      { word: 'be', timing: 0 },
      { word: 'much', timing: 0 },
      { word: 'more', timing: 0 },
      { word: 'from', timing: 0 },
      { word: 'the', timing: 0 },
      { word: 'heart', timing: 0 } ],
    [ { word: 'Forever', timing: 0 },
      { word: 'trust', timing: 0 },
      { word: 'in', timing: 0 },
      { word: 'who', timing: 0 },
      { word: 'we', timing: 0 },
      { word: 'are', timing: 0 } ],
    [ { word: 'No,', timing: 0 },
      { word: 'nothing', timing: 0 },
      { word: 'else', timing: 0 },
      { word: 'matters', timing: 0 }
    ]]
}

var connections = {}, port = 3009, host = "0.0.0.0", counter = 0

var server = 
  connect(
    connect.favicon(),
    connect.logger({ "buffer": true }),
    connect.router(function(resource) {
      resource.get("/song", function(request, response) {
        response.writeHead(200, { "Content-Type": "application/json" })
        response.end(JSON.stringify(nothingElseMatters))
      })
    }))
  .use("/static", connect.static(path.join(__dirname, "static"), { "cache": true }))
  .listen(port, host)
